### ISSUE TITLE
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.

### ISSUE THREAD

**Issue by bellstwohearted** [gnina/libmolgrid#15]
Hi,

I'm working on CentOS7, cuda9.0, anaconda3.

While I am "make"ing gnina, I got such an error:

`
Scanning dependencies of target libmolgrid_shared

[  1%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/libmolgrid.cpp.o

[  3%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/atom_typer.cpp.o

[  5%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example.cpp.o

[  7%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/exampleref_providers.cpp.o

[  9%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example_extractor.cpp.o

[ 10%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example_provider.cpp.o

[ 12%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cpp.o

[ 14%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o

nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.

In file included from /usr/include/c++/4.8.2/array:35:0,
                 from /data/AI_projects/program/gnina/build/libmolgrid/include/libmolgrid/grid_maker.h:13,
                 from /data/AI_projects/program/gnina/build/libmolgrid/src/grid_maker.cu:1:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: *** [src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o] Error 1
make[1]: *** [src/CMakeFiles/libmolgrid_shared.dir/all] Error 2
make: *** [all] Error 2
`

It seems that -std=c++11 has to be assigned during the compilation of libmolgrid. During some research on the internet, somebody said that I can add something like `CXXFLAGS=-std=c++11` in the CMakelists or in the "make" command.

However, neither of these attempts works, this error arises always during making. I also tried to install libmolgrid seperately, the same error is still there.

 I am wondering whether I am missing something??

**Comment by dkoes** [comment]
We use cxx14 features so I think your only option is to upgrade your compiler.
